# Generated by Django 5.1.1 on 2024-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book_created_at_booktype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
